name: CI
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git subtree split -P "$PKG_ROOT" -b upm-viewobject
        git push -u origin upm-viewobject
      env:
        PKG_ROOT: Packages/viewto-objects
